/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DestinationsImport } from './routes/destinations'
import { Route as IndexImport } from './routes/index'
import { Route as DestinationsSlugImport } from './routes/destinations.$slug'

// Create/Update Routes

const DestinationsRoute = DestinationsImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DestinationsSlugRoute = DestinationsSlugImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsImport
      parentRoute: typeof rootRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugImport
      parentRoute: typeof DestinationsImport
    }
  }
}

// Create and export the route tree

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/destinations/$slug': typeof DestinationsSlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/destinations/$slug': typeof DestinationsSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/destinations/$slug': typeof DestinationsSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/destinations' | '/destinations/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/destinations' | '/destinations/$slug'
  id: '__root__' | '/' | '/destinations' | '/destinations/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/destinations"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/destinations": {
      "filePath": "destinations.tsx",
      "children": [
        "/destinations/$slug"
      ]
    },
    "/destinations/$slug": {
      "filePath": "destinations.$slug.tsx",
      "parent": "/destinations"
    }
  }
}
ROUTE_MANIFEST_END */
